FROM openjdk:17
COPY . /home/tecnologo/Documentos/Coso-para-Ingenieria/carpeta2/espotify-1.0-SNAPSHOT.jar
WORKDIR /home/tecnologo/Documentos/Coso-para-Ingenieria/carpeta2


#ENTRYPOINT ["java", "-jar", "espotify-1.0-SNAPSHOT.jar"]
